Added query to wallet value
pangolindex/interface pull request #280
Opened 2022-01-20 00:17 UTC by prodesert22

### What's New
Added query to get wallet value in USD in multiples chains using Debank API

2022-01-21 16:29 UTC, SarjuHansaliya requested changes

2022-01-21 16:29 UTC, SarjuHansaliya commented on src/pages/Beta/Swap/MyPortfolio/index.tsx
> +      {!!!account ? (
lets use `!account` as `!!!` is similar to `!`

2022-01-21 16:29 UTC, SarjuHansaliya commented on src/state/news/hooks.ts
> +                    type: TypeNews[element.attributes.Type]
lets use `?` for nested operations like `element?.attributes?.title` so page doesn't crash in case attributes is undefined/null

2022-01-22 05:54 UTC, HariSeldon23 commented on src/pages/Dashboard/index.tsx
> +                  {
@SarjuHansaliya do we use an auto formatter? If so, should we include this in a contribution guide to the repo, so any new developers can understand.

2022-01-22 06:04 UTC, SarjuHansaliya commented on src/pages/Dashboard/index.tsx
> +                  {
yes we are using standard formatting guide. we have `.prettierrc` file in repo already, so if dev has prettier plugin in vscode then just need to do "Format Document".

2022-01-22 06:05 UTC, SarjuHansaliya commented on src/pages/Dashboard/index.tsx
> +                  {
Once I get some time, i am planning to integrate pre-commit rules in this repo, so all commits will be verified before it gets commited

2022-01-22 06:06 UTC, HariSeldon23 commented on src/pages/Dashboard/index.tsx
> +                  {
Sounds great mate

2022-01-25 08:06 UTC, SarjuHansaliya approved these changes

2022-01-25 08:07 UTC, merged