Patch/tests + added yarn test command to deploy.yml
pangolindex/interface pull request #465
Opened 2022-04-29 14:05 UTC by antiyro

Patched old not working tests to current version. Those tests may be outdated because they don't correspond to Pangolin v2 (they were initialy made for uniswap and never been touched since Pangolin). Also modified deploy.yml so CI is good.

2022-04-29 15:03 UTC, iam-robi commented on .github/workflows/deploy.yml
> +      - patch/tests
we can keep only for mast / dev for now

2022-04-29 15:37 UTC, antiyro commented on .github/workflows/deploy.yml
> +      - patch/tests
Just corrected it

2022-04-30 07:01 UTC, HariSeldon23 approved these changes

2022-04-30 07:02 UTC, HariSeldon23 commented
Looks good, happy to merge whenever everybody is ready

2022-05-01 15:34 UTC, SarjuHansaliya requested changes
@antiyro tests are looking good but we dont need yarn.lock file changes as there is no package.json file change. so please revert yarn.lock file then we are good to merge

2022-05-02 11:00 UTC, SarjuHansaliya approved these changes

2022-05-02 11:02 UTC, merged