Refetch the minicheft subgraph info to refresh all data from ui
pangolindex/interface pull request #571
Opened 2022-07-21 17:05 UTC by prodesert22

- Refetch minicheft subgraph info when add/remove liquidity and add/remove farm
- Show earn detail when you have liquidity to able to remove

2022-07-21 17:19 UTC, HariSeldon23 commented
Task linked: [CU-32gz8xd After removing liq you have to refresh](https://app.clickup.com/t/32gz8xd)

2022-07-26 11:45 UTC, SarjuHansaliya requested changes

2022-07-26 11:45 UTC, SarjuHansaliya commented on src/pages/Beta/Pool/DetailModal/DetailView/index.tsx
> +          <Box mt={hasliquidity ? '10px' : '0px'}>
EarnDetail is only for users who are farming. By showing EarnDetail earn details to users who just have liquidity will confuse user.

2022-07-26 11:45 UTC, SarjuHansaliya commented on src/pages/Beta/Pool/EarnWidget/AddLiquidity/index.tsx
> +      queryClient.refetchQueries(['get-minichef-farms-v2', account])
lets create utility hook something like 
`const refetchMinichefSubgraph = useRefetchMinichefSubgraph()` 
which just wrap `queryClient.refetchQueries(['get-minichef-farms-v2', account])` so we don't have to repeat everytime.

2022-07-26 11:45 UTC, SarjuHansaliya commented on src/pages/Beta/Pool/EarnWidget/Stake/index.tsx
> +          queryClient.refetchQueries(['get-minichef-farms-v2', account])
can you please try this once more ? This line didn't work for me when I did farm, It didn't updated info in left side.

2022-08-01 11:06 UTC, SarjuHansaliya commented
We have moved pools components to components repo. I have taken these changes to components PR https://github.com/pangolindex/components/pull/79. So closing this PR

2022-08-01 11:06 UTC, closed without merging